### ISSUE TITLE
Waydroid not starting

### ISSUE THREAD

**Issue by mohammedmunir** [YasirRWebDesigner/AutoDroid#6]
Hi I have ran your script and all installed without any issues.
When i run the command "waydroid show-full-ui" i get the below error.

Starting waydroid session
WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?

I'm using arch - xfce with zen kernel.
Any idea what i'm doing wrong.

**Comment by iEscapedVim** [comment]
[Waydroid](https://wiki.archlinux.org/title/Waydroid) only works on [Wayland ](https://wiki.archlinux.org/title/wayland) either install gnome or kde, if you have a low system you can also try hyprland. xfce uses x11

**Comment by mohammedmunir** [comment]
Do you have a script that i can install hyperland and waydroid? Just want to see if it works.

What commands do you use to lunch from hyperland? waydroid show-full-ui

Thanks

**Comment by iEscapedVim** [comment]
> 

Here 
https://www.youtube.com/watch?v=whAi_y_LfEE

**Comment by mohammedmunir** [comment]
Is there a way to disable the screen time out through terminal?
